### PR TITLE
Added "Sign commits" to "How to" section

### LINKED ISSUE #193: [DOCS] Adding "How to sign commits" in How To section
### Description

Hey @Pradumnasaraf ,in the [how-to](https://oswp.study/#/pages/How-to/README) section of the website, I would like to add how to sign commits, as it is a lesser known piece of information that gets necessary in open source.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by priyanshu68**
## 🛠️ Fixes Issue

  Closes #193 

## 👨‍💻 Changes proposed

1. Changed [how-to](https://oswp.study/#/pages/How-to/README) page of the site and added a new row in the table at number 23, which links to the page on how to sign commits.
2. Added new file in guide folder, sign-commit.md

## ✔️ Check List 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/209"></a>

### CODE REVIEW

**Comment by priyanshu68** [comment]
@Pradumnasaraf Can you please let me know about this Gitpod check as Iam new to Gitpod?

**Comment by priyanshu68** [comment]
@Pradumnasaraf resolved merge conflicts

**Comment by priyanshu68** [comment]
@Pradumnasaraf resolved  merge conflicts . Can you check my pr and lemme know if any more changes are required?

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
