### PR TITLE
Added Alt Description

### PR DESCRIPTION
**Pull request by YashPimple**
Resolved and Added Alt Description to  Issue #130 creating-pr.md file.

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
I can't accept this PR, You opened the PR without getting assigned to it. See the [contribution guidelines](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md)

**Comment by YashPimple** [comment]
> I can't accept this PR, You opened the PR without getting assigned to it. See the [contribution guidelines](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md)

Sorry for the inconvenience. Now onwards would get assigned to an issue and then start working on it.

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, you have added the detailed title instead of the ALT text :). Add that to the alt placeholder.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by Pradumnasaraf** [comment]
#130

**Pull request merged**
