### PR TITLE
Center the images in linking-issue-with-pr.md

### LINKED ISSUE #135: [DOCS] Center the images in `linking-issue-with-pr.md`
### Description

Link to the docs. - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/linking-issue-with-pr.md

### Screenshots

N/A

### PR DESCRIPTION
**Pull request by yung-coder**
## 🛠️ Fixes Issue
Closes #135 

## 👨‍💻 Changes proposed
Here i have tried to center the images of linking-issue-with-pr.md. Kindly review it !

## ✔️ Check List (Check all the applicable boxes) 

- [ ✅] My code follows the code style of this project.
- [ ✅] This PR does not contain plagiarized content.
- [ ✅] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
I have tried to center the images of linking-issue-with-pr.md few images from step4 , observations and result can also be centered but only if we change their resolution but they look uneven !

## 📷 Screenshots
markdown preview in vscode after changes 
markdown

### CODE REVIEW

**Comment by yung-coder** [comment]
Hey @Pradumnasaraf  i have made the changes please give it  a look and if you want me to make some more changes to this please let me know..

**Comment by hemantwasthere** [comment]
Hello @Pradumnasaraf, Can i work on this issue 🙃

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, use the syntax below to center the images

```html
<div align="center">

[![ALT]()

</div>
```

**Comment by yung-coder** [comment]
hey @Pradumnasaraf  made the changes please give it a look

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
