### PR TITLE
Updated alt text of images

### LINKED ISSUE #134: [DOCS] Improve the ALT text in the docs
### Description

Link to the docs - https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/linking-issue-with-pr.md

### Screenshots

N/A

### PR DESCRIPTION
**Pull request by PriyanshuAhlawat**
## 🛠️ Fixes Issue

closes #134 

## 👨‍💻 Changes proposed

Updated alt text of images

## ✔️ Check List (Check all the applicable boxes) 

- [✔] My code follows the code style of this project.
- [✔] This PR does not contain plagiarized content.
- [✔] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/173"></a>

### CODE REVIEW

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by PriyanshuAhlawat** [comment]
@Pradumnasaraf can u also add hacktoberfest-accepted label please🙂

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf can u also add hacktoberfest-accepted label pleaseslightly_smiling_face

After approval and merging there is no need for label, bit still adding fo you :)

**Comment by PriyanshuAhlawat** [comment]
> After approval and merging there is no need for label, bit still adding fo you :)

Thank you!

**Pull request merged**
