### PR TITLE
Add: Create-Github-Secrets

### PR DESCRIPTION
**Pull request by hasnainmakada-99**
## 👨‍💻 Changes proposed
- Added the guide to create github secrets

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/178"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

The image links are broken, just add the images through GitHub UI. Also revert the changes from `pages/How-to/guide/create-releases.md`



Screenshot from 2022-10-03 23-56-53

**Comment by hasnainmakada-99** [comment]
Ok @Pradumnasaraf I'll do it

**Comment by hasnainmakada-99** [comment]
> Hey,
> 
> The image links are broken, just add the images through GitHub UI. Also revert the changes from `pages/How-to/guide/create-releases.md`
> 
> Screenshot from 2022-10-03 23-56-53

@Pradumnasaraf I've made the required changes which you told me and fixed the broken images link

**Comment by ChinmayMhatre** [comment]
The images look good.

**Pull request merged**
