### PR TITLE
fix formatting issue in README.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## 🛠️ Fixes Issue
- fix formatting issue in last section of the README.md
   - It's not supposed to be = "align" , it's supposed to be ="align".

## 👨‍💻 Changes proposed
-  fix formatting issue in last section of the README.md

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
This problem is fixed in a branch, so it will create a merge conflict
Thank you fo for the PR.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Tags:** Not reusable

**Comment by KendallDoesCoding** [comment]
> This problem is fixed in a branch, so it will create a merge conflict, not merging it Thank you fo for the PR.
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix  |  **Tags:** Not reusable

What can I do to resolve this?

**Comment by Pradumnasaraf** [comment]
Hey! Kendall the problem is already fixed in a branch, need to merge that

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by KendallDoesCoding** [comment]
> Hey! Kendall the problem is already fixed in a branch, need to merge that
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Ok cool.

**Pull request closed without merging**
