### PR TITLE
docs: Improve the steps in `cloning-repo.md`

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**
## 🛠️ Fixes Issue

Documentation enhancement.

## 👨‍💻 Changes proposed

Added directions on how to paste a link in the Git Bash terminal with added screenshots for beginners.

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, Thank you for the PR.

### Changes required
- Center all the images

**Comment by kelvinparmar** [comment]
Hey @Pradumnasaraf what changes have to do?

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf what changes have to do?

I have already above, @ShubhamJagtap2000 will do that when they see that.
Thank you!

**Comment by ShubhamJagtap2000** [comment]
> Hey, Thank you for the PR.
> ### Changes required
> 
>     * Center all the images

**Comment by ShubhamJagtap2000** [comment]
Okay I will do the changes

**Review by ShubhamJagtap2000 — COMMENTED** [review]
All images are now aligned at the center, check once.

**Comment by ShubhamJagtap2000** [comment]
> > Hey @Pradumnasaraf what changes have to do?
> 
> I have already explained above. @ShubhamJagtap2000 will do that when they see that. Thank you!

Hello @Pradumnasaraf, can review the changes?

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by ShubhamJagtap2000** [comment]
> Looks good to merge. Thank you for your contribution! 🎉

Thank you @Pradumnasaraf. I am really loving to be a part of your great initiative.

**Pull request merged**
