### PR TITLE
Update create-licence.md

### LINKED ISSUE #182: [DOCS] Update create-license.md
### Description

I regularly follow your repo updates and look over whatever info is added. I can see an irregular structure of numbers in create-license.md for points no. 5, 6, and 7. Every point should start in a new line. (shown in the screenshot below)

I would also like to make a `table of licenses and a short description of it` that is included in the YouTube video link mentioned in the file so that one could easily understand which license does what and for details video is better. It will also enhance the quality of documentation.

Should I continue??

### Screenshots

image

### PR DESCRIPTION
**Pull request by ShubhamJagtap2000**
## 🛠️ Fixes Issue

Closes #182 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/187"></a>

### CODE REVIEW

**Comment by ShubhamJagtap2000** [comment]
Don't know but GitPod is taking too much time to rebuild. Please review the changes made @Pradumnasaraf

**Comment by Pradumnasaraf** [comment]
> Don't know but GitPod is taking too much time to rebuild. Please review the changes made @Pradumnasaraf

Thanks for your feedback, need to work around that.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by ShubhamJagtap2000** [comment]
> > Don't know but GitPod is taking too much time to rebuild. Please review the changes made @Pradumnasaraf
> 
> Thanks for your feedback, need to work around that.

Already started referring your repo to friends and the other community.

**Pull request merged**
