### PR TITLE
docs: Add process "How to add social preview to a repo"

### LINKED ISSUE #93: [DOCS] Add process/guide - "How to add a social preview to a repo"
### Description

Hey! Contributor,

This issue is for adding a guide/process for **How to add a social preview to a repo**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/social-preview.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/social-preview.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

### PR DESCRIPTION
**Pull request by AbbeyIT**
## 🛠️ Fixes Issue
Closes #93

## 👨‍💻 Changes proposed
Added a step-by-step guide on how to add a social preview to a repository 

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Thank you for the PR. Can put both images in a single line.

Screenshot from 2022-09-11 18-47-31

**Comment by AbbeyIT** [comment]
@Pradumnasaraf Done.

**Review by Pradumnasaraf — APPROVED** [review]
Thank you so much for the changes. Looks good to merge :tada:

**+** I have fixed a minor couple of syntax according to hosting support for you. And convert the video into GIF and it's currently not supported directly with a markdown tag







__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by AbbeyIT** [comment]
Thank you @Pradumnasaraf I am happy to contribute!

**Pull request merged**
