### PR TITLE
Fix #190: Typo in pages/How-to/README.md

### LINKED ISSUE #190: [DOCS] Typo and grammatical errors in README.md of How-to
### Description

There are some notable grammatical errors present in the README.md file of pages/How-to.

### Screenshots

image

### PR DESCRIPTION
**Pull request by getRicha**
## 👨‍💻 Changes proposed
- Fixed a few typos in the markdown

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/191"></a>

### CODE REVIEW

**Review by hasnainmakada-99 — APPROVED** [review]
Looks good to me

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by getRicha** [comment]
Hi @Pradumnasaraf, can you please add the hacktoberfest-accepted label.

**Comment by Pradumnasaraf** [comment]
> Hi @Pradumnasaraf, can you please add the hacktoberfest-accepted label.

Typos are grammar are not counted towards this hacktoberfest.

**Pull request merged**
