### PR TITLE
docs: Add process "How to create a Releases - Manually"

### PR DESCRIPTION
**Pull request by hasnainmakada-99**
## 👨‍💻 Changes proposed
Added the `create-release.md` file which describes on how to create releases on your repository

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

To make the image work there should be space between the line and points. Also, it look very similar to GitHub official docs and needs to be more simplified

Also, for images use githubusercontent image, your current giving a 404 

Screenshot from 2022-09-14 22-13-12

**Comment by hasnainmakada-99** [comment]
Ok @Pradumnasaraf I'll make the changes

**Comment by hasnainmakada-99** [comment]
@Pradumnasaraf will you please review it

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution :tada:!!

(Image needs to center. I will open another issue for that)

**Pull request merged**
