### PR TITLE
docs: Added process "Adding a sponsor button"

### LINKED ISSUE #13: [DOCS] Add process/guide - "How to add sponsor button to a repo"
### Changes/Action required
 
 - Add a complete process of **"Adding sponser to a repo"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/adding-sponsor.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-sponsor.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

Screenshot from 2022-05-15 14-11-21

### PR DESCRIPTION
**Pull request by singh-saksham**
## 🛠️ Fixes Issue
Closes #13 

## 👨‍💻 Changes proposed

Added a step-by-step guide to add the sponsor button.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots
image

### CODE REVIEW

**Review by Jai-Solania-29 — CHANGES_REQUESTED** [review]
Hey, @singh-saksham I have suggested some changes, Please go through them.
There is one more suggestion, We can also put some gap between the Heading/Paragraph and the Images.
Hey, @Pradumnasaraf I would also like to know your views regarding the same.

**Comment by singh-saksham** [comment]
@Jai-Solania-29 Thanks for your suggestions, Sorry for the late reply. Will do the changes ASAP

**Comment by singh-saksham** [comment]
@Jai-Solania-29 Do I have to update the Screenshot also that I attached in the PR.

**Comment by Pradumnasaraf** [comment]
> Hey, @singh-saksham I have suggested some changes, Please go through them. There is one more suggestion, We can also put some gap between the Heading/Paragraph and the Images. Hey, @Pradumnasaraf I would also like to know your views regarding the same.

All good, thank you, Jai for the review. :smile:

**Comment by Jai-Solania-29** [comment]
> @Jai-Solania-29 Do I have to update the Screenshot also that I attached in the PR.

No, Let it stay the same.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by singh-saksham** [comment]
@Pradumnasaraf done all the changes asked

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge :tada:. Thank you for your valuable contribution

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Review by Jai-Solania-29 — APPROVED** [review]
LGTM 🚀

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by singh-saksham** [comment]
@Pradumnasaraf Hey it has not been merged is there a revision required?

**Comment by Pradumnasaraf** [comment]
Thank you for your patience, there was some bug with GitHub, I was not able to squash the commits, and now it looks good!

**Pull request merged**
