### PR TITLE
docs: Add process for "How to create a project board"

### LINKED ISSUE #99: [DOCS] Add process/guide - "How to create to create GitHub project board"
### Description

Hey! Contributor,

This issue is for adding the guide/process for **How to create to create GitHub project board**. The step needs to be well defined and include the Screenshot/Screen recording for better explanation. To get an overview of how the docs should look, check the available docs [`here`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide)

- Path to the dedicate Markdown for this issue - [`open-source-with-pradumna/pages/How-to/guide/create-project-board.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/create-project-board.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

**Also if you need any kind of help, feel free to ping!**

### PR DESCRIPTION
**Pull request by kelvinparmar**
## 🛠️ Fixes Issue

closes #99 

## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/164"></a>

### CODE REVIEW

**Comment by yash251** [comment]
You should put "x" in the squared brackets to see tasks in the PR @kelvinparmar

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey, use the image link generated by GitHub instead of storing the image in the repo. You drag and drop to generate a link.

**Comment by kelvinparmar** [comment]
How to create image link?
I don't have any idea

**Comment by Pradumnasaraf** [comment]
Add images in the markdown directly from the GitHub UI by catching them.

something like this

https://user-images.githubusercontent.com/51878265/193461070-5141f920-9167-40cb-b9d5-7522274453d1.mp4

**Comment by kelvinparmar** [comment]
Hey @Pradumnasaraf  I have updated images URL.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Pull request merged**
