### PR TITLE
fix: Updated typo in `How to`

### PR DESCRIPTION
**Pull request by kelvinparmar**
## ✔️ Check List (Check all the applicable boxes) 

- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey Please use the hyperlink that I provided in issue #75. We don't store it locally on the repo.
If you have any doubt feel free to reach out.

**Comment by kelvinparmar** [comment]
But I am not able to download any images means it's only save html format

**Comment by Pradumnasaraf** [comment]
> But I am not able to download any images means it's only save HTML format 

You don't need to download you can just use that URL in place on my old URL

**Comment by kelvinparmar** [comment]
But where I have to put it that canva link that you have provided me

**Comment by Pradumnasaraf** [comment]
> But where I have to put it that can link that you have provided me 

Check the issue. I have added a comment with two link of the image

**Comment by kelvinparmar** [comment]
Hey @Pradumnasaraf please check it. I have updated

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf It's ok or not?

Hey, as I mention my exams are going

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your valuable contribution. 🎉 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome&nbsp; | &nbsp;**Tags:** Maintainable

**Comment by kelvinparmar** [comment]
Sorry @Pradumnasaraf 
Thank you for your valuable time 🙂

**Pull request merged**
