### PR TITLE
docs: Add "How to create an Issue" in `How to` guide

### LINKED ISSUE #12: [DOCS] Add process/guide - "How to create an Issue"
### Changes/Action required
 
 - Add a complete process of "How to create an Issue", steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/rasing-issue.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/rasing-issue.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)
 

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

Screenshot from 2022-05-15 14-11-21

### PR DESCRIPTION
**Pull request by akebu6**
## 🛠️ Fixes Issue
This PR closes #12. Had issues with loading the images but got it fixed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

Kindly offer feedback on what should be added or removed 

## 📷 Screenshots
Screenshot (828)

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey! Akebu some changes required

- There is a file created in the root folder `creating-an-issue.md` with the same content addition can you please delete that.
- Instead of using the physical link, can you please use a drag and drop link (Link generated when you drop something on GitHub)

And Thank you for the detailed docs, look amazing. Let me know if you have any doubt.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by akebu6** [comment]
I have been having issues with using GitHub directly that's why I used the images in that light. I am still having that issue, Even if I drag and drop the files, they don't appear and the commit changes button is greyed out. I've been trying to figure out what's happening for the last 2 days now😥

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by akebu6** [comment]
The issue is also happening with repos as well. Would you happen to know what's going on? I tried logging out and back in but I'm still having the same issue

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by Pradumnasaraf** [comment]
> I have been having issues with using GitHub directly that's why I used the images in that light. I am still having that issue, Even if I drag and drop the files, they don't appear and the commit changes button is greyed out. I've been trying to figure out what's happening for the last 2 days nowdisappointed_relieved
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  

That's is little weird, you can drop the problem with the screenshot in EddieHub i will help you out in that.__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by Pradumnasaraf** [comment]
> The issue is also happening with repos as well. Would you happen to know what's going on? I tried logging out and back in but I'm still having the same issue
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  

Hey, @akebu6 looks like you have fixed all the issues, Woohoo.

**Comment by akebu6** [comment]
Awesome, I really liked working on this because I also got to learn a lot from the process. For the other issue regarding **raising an issue** how does that differ from this one? 

Is that one more on using an already provided Issue Template?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Comment by Pradumnasaraf** [comment]
> Awesome, I really liked working on this because I also got to learn a lot from the process. For the other issue regarding **raising an issue** how does that differ from this one?
> 
> Is that one more on using an already provided Issue Template?
> 
> __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  

Glad you learn during the process. 

Yes the other issue https://github.com/Pradumnasaraf/open-source-with-pradumna/issues/18, if I am not getting the issue wrong that you are taking, it's about adding Issue templates instead of opening and issue.

**Comment by akebu6** [comment]
Oh, I see. I look forward to working on this repo and getting to learn a lot in the process :-)
Thanks for the opportunity Pradumna🙏

**Comment by Pradumnasaraf** [comment]
> Oh, I see. I look forward to working on this repo and getting to learn a lot in the process :-) Thanks for the opportunity Pradumnapray

No, Thank you, with CommUNITY supporters like you, this repo will remain incomplete.
And again sorry for the ping!.

**Approving** and **Merging** this PR

**Comment by akebu6** [comment]
It's all right, the ping shows you are really active with the repo and I appreciated it :-)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by Pradumnasaraf** [comment]
Your contribution is live at [https://opensource.pradumnasaraf.co/#/pages/How-to/guide/rasing-issue](https://opensource.pradumnasaraf.co/#/pages/How-to/guide/rasing-issue)

**Pull request merged**
