### PR TITLE
Add contributing guidelines

### LINKED ISSUE #23: [DOCS] Add contribution guidelines
The contribution guide should be sectioned and specific to [pages](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages).

If the pages have a similar pattern put them in one section,

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## 🛠️ Fixes Issue
- The repo doesn't have any CONTRIBUTING Guidelines as of now, so I added some basic guidelines as requested in #23 

Fixes #23 

## 👨‍💻 Changes proposed
- add basic contributing guidelines

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
hope this works

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Looks great @kendal can you add a little bit about `How to` ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by KendallDoesCoding** [comment]
> Looks great @Kendal can you add a little bit about `How to`?
> 
> __ [sema-logo](https://semasoftware.com/gh)  **Summary:** 🛠️ This code needs a fix

Thanks!

Sure, will work on that later in the day.

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf Hope this works, As and when the guide files get updated, I will update the Guidelines too, if required.

Let me know if you need anything.

Sorry for the delay,
KendallDoesCoding

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to me!

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
