### PR TITLE
Added the process to Review a Pull Request

### LINKED ISSUE #20: [DOCS] Add process/guide - "How to review a PR"
### Changes/Action required
 
 - Add a complete process of **"How to review a PR"**, steps will contain a text, screenshot, Video (it can be a screen recording to show the steps), and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/reviewing-pr.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/reviewing-pr.md)

---

If you have any suggestions feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

Screenshot from 2022-05-15 14-11-21

### PR DESCRIPTION
**Pull request by Jai-Solania-29**
## 🛠️ Fixes Issue
Closes #20 

## 👨‍💻 Changes proposed
Successfully added the process to Review a Pull Request.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Pradumnasaraf — COMMENTED** [review]
Hey!
Thank you for opening the PR. it looks wonderful. Can you add a line just above the _Starting a review_ saying. 

`Note: You need not be a maintainer or a  project admin to to review a PR`

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Comment by Jai-Solania-29** [comment]
Hey @Pradumnasaraf , just a little confusion. Do I need to add this in a highlighted format as written by you, or just simply type it ?
1 :
NOTE 1
2 :
NOTE 2

**Review by Pradumnasaraf — COMMENTED** [review]
You can add the simple one. Also please remove the changes in the PR from the previous one (Favicon one)

**Comment by Jai-Solania-29** [comment]
Hey Pradumna I'm not getting you , Those are my previous changes I haven't made them this time. Can you please elaborate a little more about it ?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
I mean changes from PR is also present in this PR. Please remove them
Screenshot 2022-07-18 at 9 25 27 PM

**Comment by Jai-Solania-29** [comment]
Hey @Pradumnasaraf Actually I'm facing some problem with this PR. I don't know why the previous changes are reflecting here, And as you told me to delete the favicon part from the PR, I have deleted the index.html but I'm unable to delete the favicon as it is not showing any option to delete it.

PR error

So I'm closing this PR and will make a new PR with the respective changes.

**Pull request closed without merging**
