### PR TITLE
docs: Add process "How to archive a repo" 

### PR DESCRIPTION
**Pull request by Lokeshkhati**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
**Thank you so much for the PR.**
There are some changes required
- Center the images

If you need any help. Feel free to ping me.

**Comment by Lokeshkhati** [comment]
@Pradumnasaraf   Thank you so much for your feedback.
 
I will make the required the changes.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution :tada:

**Comment by Lokeshkhati** [comment]
@Pradumnasaraf Thank you.

**Pull request merged**
