### PR TITLE
Mark starting a discussion as done in How-to README.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## 🛠️ Fixes Issue
- Starting a discussion is done although, it's still marked as PROCESS

## 👨‍💻 Changes proposed
- Mark starting a discussion as done in How-to README.md

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey! Kendall the current text is correct `PROCESS`. If it was `processing` then it might be wrong, thank you for your PR.

**CLOSING FOR NOW**

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by KendallDoesCoding** [comment]
> Hey! Kendall the current text is correct `PROCESS`. If it was `processing` then it might be wrong, thank you for your PR.

wdym? it should be marked as DONE right?

**Comment by Pradumnasaraf** [comment]
> > Hey! Kendall the current text is correct `PROCESS`. If it was `processing` then it might be wrong, thank you for your PR.
> 
> wdym? it should be marked as DONE right?

No, it says the **PROCESS** which means you can learn the process from it. It's correct.We can find better word later on, Thank you

**Comment by KendallDoesCoding** [comment]
Oh ok, makes sense.

**Pull request closed without merging**
