### PR TITLE
center the images in the review_pr.md file

### PR DESCRIPTION
**Pull request by kakkarot0**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

<a href="https://gitpod.io/#https://github.com/Pradumnasaraf/open-source-with-pradumna/pull/171"></a>

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
**Hey, thank you for raising the PR.**

### :wrench: Chnages required
Keep the markdown syntax for the images, instead of changing it into an HTML element. In this way, You can do it.

```HTML

<div align="center">
// Blank line
[![ALT](https://.......)
// Blank line
</div>
```

**Comment by kakkarot0** [comment]
ok i'll correct this

**Comment by kakkarot0** [comment]
sorry pradumnasaraf but did you get the pull request and let me know if theres more work to do

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for your contribution! :tada:

**Comment by kakkarot0** [comment]
Thanks to you

**Pull request merged**
