### PR TITLE
docs: Add process - "how to create a PR Template"

### LINKED ISSUE #11: [DOCS] Add process - "how to create a PR Template"
### Changes/Action required
 
 - Add a complete process of **how to create a PR**, steps will contain a text, screenshot, Video (it can be screen recording to show the steps) and GIF (if needed)
 
- Path of the file in which **steps** need to be added - [`open-source-with-pradumna/pages/How-to/guide/adding-pr-template.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/pages/How-to/guide/adding-pr-template.md)

---

If you have any suggestion feel free to Open an [Issue](https://github.com/Pradumnasaraf/open-source-with-pradumna/issues)
 

#### This addition of the documentation will get added and hyperlinked in [`How-to/README.md`](https://github.com/Pradumnasaraf/open-source-with-pradumna/tree/main/pages/How-to) and also get hosted on the website https://Opensource.pradumnasaraf.co

Screenshot from 2022-05-15 14-11-21

### PR DESCRIPTION
**Pull request by SuperAayush**
## 🛠️ Fixes Issue

Closes #11 

## 👨‍💻 Changes proposed

Added the complete procedure to be followed in order to make a PR Template.
Added a demo video with all the related screen shots 
## ✔️ Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

cc - @Pradumnasaraf 
## 📷 Screenshots

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey! @SuperAayush PR looks awesome, thank you for the effort. I think this time we should add the one process only because for beginners it can little overwhelming at the start.

Here are the changes needed:
- Only Add process for `.github/pull_request_tempalte.md` which is the standard one.
- Reduce the video length accordingly
- Some points required like using backticks in important terms like `.github/...`

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

**Comment by Pradumnasaraf** [comment]
Hey Aayush waiting for the required changes, if you have doubts feel free to ask

**Comment by SuperAayush** [comment]
Hey @Pradumnasaraf, can you explain the third point a bit more 😄

> Hey! @SuperAayush PR looks awesome, thank you for the effort. I think this time we should add the one process only because for beginners it can little overwhelming at the start.
> 
> Here are the changes needed:
> 
> * Only Add process for `.github/pull_request_tempalte.md` which is the most used and somewhere standard one.
> * Reduce the video length accordingly
> * Some points required like using backticks in important terms like `.github/...`
> 
> Again, thank you for opening the PR, if you need any help feel free to reach out. __ [sema-logo](https://semasoftware.com/gh) [ sema-logo ](https://semasoftware.com/gh) [ ](https://semasoftware.com/gh)  🛠️ This code needs a fix

**Comment by Pradumnasaraf** [comment]
Hey Aayush,
I mean, you can highlight some important keywords with Backticks (``)

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for the changes and valuable contribution and time.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good&nbsp; | &nbsp;**Tags:** Reusable

**Pull request merged**
